
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class Entrada
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Label label9;

		private global::Gtk.Label lblHora;

		private global::Gtk.Calendar calendar1;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Button btnEntrada;

		private global::Gtk.Button btnSalida;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry txtTipoDeMarca;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.Entrada
			this.Name = "COntrolREyS.Entrada";
			this.Title = global::Mono.Unix.Catalog.GetString("Entrada");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.Entrada.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("¡BIenvenido Empleado!");
			this.vbox12.Add(this.label9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.lblHora = new global::Gtk.Label();
			this.lblHora.Name = "lblHora";
			this.lblHora.LabelProp = global::Mono.Unix.Catalog.GetString("Reloj");
			this.vbox12.Add(this.lblHora);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.lblHora]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox12.Add(this.calendar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.calendar1]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.fixed3.Add(this.vbox12);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.vbox12]));
			w4.X = 17;
			w4.Y = 11;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.btnEntrada = new global::Gtk.Button();
			this.btnEntrada.CanFocus = true;
			this.btnEntrada.Name = "btnEntrada";
			this.btnEntrada.UseUnderline = true;
			this.btnEntrada.Label = global::Mono.Unix.Catalog.GetString("Marcar");
			this.hbox21.Add(this.btnEntrada);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.btnEntrada]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.btnSalida = new global::Gtk.Button();
			this.btnSalida.CanFocus = true;
			this.btnSalida.Name = "btnSalida";
			this.btnSalida.UseUnderline = true;
			this.btnSalida.Label = global::Mono.Unix.Catalog.GetString("Confirmar");
			this.hbox21.Add(this.btnSalida);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.btnSalida]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.fixed3.Add(this.hbox21);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.hbox21]));
			w7.X = 353;
			w7.Y = 184;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrese su cedula y marque");
			this.vbox13.Add(this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.WidthRequest = 222;
			this.txtNombre.HeightRequest = 0;
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.vbox13.Add(this.txtNombre);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.txtNombre]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.fixed3.Add(this.vbox13);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.vbox13]));
			w10.X = 302;
			w10.Y = 125;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Escriba Entrada o Salida");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.txtTipoDeMarca = new global::Gtk.Entry();
			this.txtTipoDeMarca.WidthRequest = 222;
			this.txtTipoDeMarca.CanFocus = true;
			this.txtTipoDeMarca.Name = "txtTipoDeMarca";
			this.txtTipoDeMarca.IsEditable = true;
			this.txtTipoDeMarca.InvisibleChar = '•';
			this.vbox1.Add(this.txtTipoDeMarca);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.txtTipoDeMarca]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.fixed3.Add(this.vbox1);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.vbox1]));
			w13.X = 296;
			w13.Y = 45;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 546;
			this.DefaultHeight = 264;
			this.Show();
			this.btnEntrada.Clicked += new global::System.EventHandler(this.OnBtnEntradaClicked);
			this.btnSalida.Clicked += new global::System.EventHandler(this.OnBtnSalidaClicked);
		}
	}
}
