
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class ReporteCargo
	{
		private global::Gtk.Fixed fixed5;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Label label11;

		private global::Gtk.ScrolledWindow scrolledwindow6;

		private global::Gtk.TreeView TvListaCargo;

		private global::Gtk.Button button10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.ReporteCargo
			this.Name = "COntrolREyS.ReporteCargo";
			this.Title = global::Mono.Unix.Catalog.GetString("ReporteCargo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.ReporteCargo.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Reporte de cargos");
			this.vbox15.Add(this.label11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.label11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.scrolledwindow6 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow6.WidthRequest = 820;
			this.scrolledwindow6.HeightRequest = 300;
			this.scrolledwindow6.CanFocus = true;
			this.scrolledwindow6.Name = "scrolledwindow6";
			this.scrolledwindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow6.Gtk.Container+ContainerChild
			this.TvListaCargo = new global::Gtk.TreeView();
			this.TvListaCargo.CanFocus = true;
			this.TvListaCargo.Name = "TvListaCargo";
			this.scrolledwindow6.Add(this.TvListaCargo);
			this.vbox15.Add(this.scrolledwindow6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.scrolledwindow6]));
			w3.Position = 1;
			// Container child vbox15.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.vbox15.Add(this.button10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.button10]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.fixed5.Add(this.vbox15);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.vbox15]));
			w5.X = 23;
			w5.Y = 20;
			this.Add(this.fixed5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 868;
			this.DefaultHeight = 411;
			this.Show();
			this.button10.Clicked += new global::System.EventHandler(this.OnButton10Clicked);
		}
	}
}
