
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class Exportar
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		private global::Gtk.Button button5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.Exportar
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "COntrolREyS.Exportar";
			this.Title = global::Mono.Unix.Catalog.GetString("Exportar");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.Exportar.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("PDF");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w2.X = 2;
			w2.Y = 16;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Excel");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w3.X = 101;
			w3.Y = 15;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.button5);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
			w4.X = 231;
			w4.Y = 15;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 372;
			this.DefaultHeight = 70;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
			this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		}
	}
}
