
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class REmpleado
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Label label9;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView TvListaReempleado;

		private global::Gtk.Button button14;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.REmpleado
			this.Name = "COntrolREyS.REmpleado";
			this.Title = global::Mono.Unix.Catalog.GetString("REmpleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.REmpleado.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Verificacion de empleado");
			this.vbox14.Add(this.label9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 700;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvListaReempleado = new global::Gtk.TreeView();
			this.TvListaReempleado.WidthRequest = 376;
			this.TvListaReempleado.HeightRequest = 311;
			this.TvListaReempleado.CanFocus = true;
			this.TvListaReempleado.Name = "TvListaReempleado";
			this.GtkScrolledWindow.Add(this.TvListaReempleado);
			this.vbox14.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox14.Gtk.Box+BoxChild
			this.button14 = new global::Gtk.Button();
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.button14.Label = global::Mono.Unix.Catalog.GetString("Cerrar Sesión");
			this.vbox14.Add(this.button14);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.button14]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.fixed3.Add(this.vbox14);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.vbox14]));
			w5.X = 35;
			w5.Y = 8;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 767;
			this.DefaultHeight = 415;
			this.Show();
			this.button14.Clicked += new global::System.EventHandler(this.CLick);
		}
	}
}
