
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class frmGuardarEmpleado
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Entry txtEmail;

		private global::Gtk.Entry txtEstado;

		private global::Gtk.Entry txtDireccion;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.Entry txtApellidos;

		private global::Gtk.Entry txtTelefono;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Entry txtCedula;

		private global::Gtk.ComboBox cbxCargo;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button btnRegresar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.frmGuardarEmpleado
			this.Name = "COntrolREyS.frmGuardarEmpleado";
			this.Title = global::Mono.Unix.Catalog.GetString("frmGuardarEmpleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.frmGuardarEmpleado.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 20;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula");
			this.vbox6.Add(this.label7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label7]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Cargo");
			this.vbox6.Add(this.label8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label8]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.fixed2.Add(this.vbox6);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vbox6]));
			w3.X = 27;
			w3.Y = 279;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 20;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.vbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos");
			this.vbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono");
			this.vbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.fixed2.Add(this.vbox2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vbox2]));
			w7.X = 11;
			w7.Y = 44;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 8;
			// Container child vbox5.Gtk.Box+BoxChild
			this.txtEmail = new global::Gtk.Entry();
			this.txtEmail.WidthRequest = 222;
			this.txtEmail.CanFocus = true;
			this.txtEmail.Name = "txtEmail";
			this.txtEmail.IsEditable = true;
			this.txtEmail.InvisibleChar = '•';
			this.vbox5.Add(this.txtEmail);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.txtEmail]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.txtEstado = new global::Gtk.Entry();
			this.txtEstado.WidthRequest = 79;
			this.txtEstado.CanFocus = true;
			this.txtEstado.Name = "txtEstado";
			this.txtEstado.IsEditable = true;
			this.txtEstado.InvisibleChar = '•';
			this.vbox5.Add(this.txtEstado);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.txtEstado]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.txtDireccion = new global::Gtk.Entry();
			this.txtDireccion.WidthRequest = 222;
			this.txtDireccion.CanFocus = true;
			this.txtDireccion.Name = "txtDireccion";
			this.txtDireccion.IsEditable = true;
			this.txtDireccion.InvisibleChar = '•';
			this.vbox5.Add(this.txtDireccion);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.txtDireccion]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.fixed2.Add(this.vbox5);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vbox5]));
			w11.X = 85;
			w11.Y = 156;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 20;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Email");
			this.vbox4.Add(this.label4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label4]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.vbox4.Add(this.label5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label5]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion");
			this.vbox4.Add(this.label6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label6]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.fixed2.Add(this.vbox4);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vbox4]));
			w15.X = 14;
			w15.Y = 160;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 8;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.WidthRequest = 222;
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.vbox3.Add(this.txtNombre);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.txtNombre]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtApellidos = new global::Gtk.Entry();
			this.txtApellidos.WidthRequest = 222;
			this.txtApellidos.CanFocus = true;
			this.txtApellidos.Name = "txtApellidos";
			this.txtApellidos.IsEditable = true;
			this.txtApellidos.InvisibleChar = '•';
			this.vbox3.Add(this.txtApellidos);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.txtApellidos]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtTelefono = new global::Gtk.Entry();
			this.txtTelefono.CanFocus = true;
			this.txtTelefono.Name = "txtTelefono";
			this.txtTelefono.IsEditable = true;
			this.txtTelefono.InvisibleChar = '•';
			this.vbox3.Add(this.txtTelefono);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.txtTelefono]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.fixed2.Add(this.vbox3);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vbox3]));
			w19.X = 86;
			w19.Y = 41;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 8;
			// Container child vbox7.Gtk.Box+BoxChild
			this.txtCedula = new global::Gtk.Entry();
			this.txtCedula.WidthRequest = 222;
			this.txtCedula.CanFocus = true;
			this.txtCedula.Name = "txtCedula";
			this.txtCedula.IsEditable = true;
			this.txtCedula.InvisibleChar = '•';
			this.vbox7.Add(this.txtCedula);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.txtCedula]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.cbxCargo = global::Gtk.ComboBox.NewText();
			this.cbxCargo.Name = "cbxCargo";
			this.vbox7.Add(this.cbxCargo);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.cbxCargo]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.fixed2.Add(this.vbox7);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vbox7]));
			w22.X = 84;
			w22.Y = 274;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbox4.Add(this.btnGuardar);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnGuardar]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.hbox4.Add(this.btnRegresar);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnRegresar]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.fixed2.Add(this.hbox4);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.hbox4]));
			w25.X = 114;
			w25.Y = 359;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 349;
			this.DefaultHeight = 438;
			this.Show();
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
		}
	}
}
