
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class ReporteEmpleado
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Label label9;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView TvListaEmpleado;

		private global::Gtk.Button button8;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.ReporteEmpleado
			this.WidthRequest = 0;
			this.HeightRequest = 0;
			this.Name = "COntrolREyS.ReporteEmpleado";
			this.Title = global::Mono.Unix.Catalog.GetString("ReporteEmpleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.ReporteEmpleado.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Reporte de Empleado");
			this.vbox16.Add(this.label9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.WidthRequest = 900;
			this.GtkScrolledWindow1.HeightRequest = 300;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.TvListaEmpleado = new global::Gtk.TreeView();
			this.TvListaEmpleado.CanFocus = true;
			this.TvListaEmpleado.Name = "TvListaEmpleado";
			this.GtkScrolledWindow1.Add(this.TvListaEmpleado);
			this.vbox16.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.GtkScrolledWindow1]));
			w3.Position = 1;
			// Container child vbox16.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.vbox16.Add(this.button8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.button8]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.fixed2.Add(this.vbox16);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vbox16]));
			w5.X = 23;
			w5.Y = 26;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 955;
			this.DefaultHeight = 415;
			this.Show();
			this.button8.Clicked += new global::System.EventHandler(this.OnButton8Clicked);
		}
	}
}
