
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class frmGuardarDepartamento
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.Button btnAlmacenar;

		private global::Gtk.Button btnRegresar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.frmGuardarDepartamento
			this.Name = "COntrolREyS.frmGuardarDepartamento";
			this.Title = global::Mono.Unix.Catalog.GetString("frmGuardarDepartamento");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.frmGuardarDepartamento.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 23;
			w1.Y = 33;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.fixed1.Add(this.txtNombre);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtNombre]));
			w2.X = 97;
			w2.Y = 29;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAlmacenar = new global::Gtk.Button();
			this.btnAlmacenar.CanFocus = true;
			this.btnAlmacenar.Name = "btnAlmacenar";
			this.btnAlmacenar.UseUnderline = true;
			this.btnAlmacenar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btnAlmacenar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAlmacenar]));
			w3.X = 74;
			w3.Y = 76;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.btnRegresar);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnRegresar]));
			w4.X = 171;
			w4.Y = 74;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 293;
			this.DefaultHeight = 141;
			this.Show();
			this.btnAlmacenar.Clicked += new global::System.EventHandler(this.OnBtnAlmacenarClicked);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
		}
	}
}
