
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class AdminDepartamento
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button BtnModificar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtEstado;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Entry txtId;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Button btnRegresar;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Label label7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView TvListaDepartamentoA;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Button BtnBuscar;

		private global::Gtk.Entry txtBuscar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.AdminDepartamento
			this.Name = "COntrolREyS.AdminDepartamento";
			this.Title = global::Mono.Unix.Catalog.GetString("AdminDepartamento");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.AdminDepartamento.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox6.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnAgregar]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.BtnModificar = new global::Gtk.Button();
			this.BtnModificar.CanFocus = true;
			this.BtnModificar.Name = "BtnModificar";
			this.BtnModificar.UseUnderline = true;
			this.BtnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.hbox6.Add(this.BtnModificar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.BtnModificar]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.hbox6.Add(this.btnEliminar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnEliminar]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.fixed1.Add(this.hbox6);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox6]));
			w4.X = 8;
			w4.Y = 180;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.hbox9.Add(this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.hbox9.Add(this.txtNombre);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.txtNombre]));
			w6.Position = 1;
			this.fixed1.Add(this.hbox9);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox9]));
			w7.X = 8;
			w7.Y = 57;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.hbox10.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.txtEstado = new global::Gtk.Entry();
			this.txtEstado.CanFocus = true;
			this.txtEstado.Name = "txtEstado";
			this.txtEstado.IsEditable = true;
			this.txtEstado.InvisibleChar = '•';
			this.hbox10.Add(this.txtEstado);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.txtEstado]));
			w9.Position = 1;
			this.fixed1.Add(this.hbox10);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox10]));
			w10.X = 16;
			w10.Y = 96;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.txtId = new global::Gtk.Entry();
			this.txtId.CanFocus = true;
			this.txtId.Name = "txtId";
			this.txtId.IsEditable = true;
			this.txtId.InvisibleChar = '•';
			this.vbox9.Add(this.txtId);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.txtId]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.fixed1.Add(this.vbox9);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vbox9]));
			w12.X = 69;
			w12.Y = 18;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.hbox11.Add(this.btnRegresar);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.btnRegresar]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			this.fixed1.Add(this.hbox11);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox11]));
			w14.X = 80;
			w14.Y = 220;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Bienvenido a registro de departamentos!");
			this.vbox8.Add(this.label7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label7]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 500;
			this.GtkScrolledWindow.HeightRequest = 0;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvListaDepartamentoA = new global::Gtk.TreeView();
			this.TvListaDepartamentoA.WidthRequest = 400;
			this.TvListaDepartamentoA.HeightRequest = 200;
			this.TvListaDepartamentoA.CanFocus = true;
			this.TvListaDepartamentoA.Name = "TvListaDepartamentoA";
			this.GtkScrolledWindow.Add(this.TvListaDepartamentoA);
			this.vbox8.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.GtkScrolledWindow]));
			w17.Position = 1;
			this.fixed1.Add(this.vbox8);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vbox8]));
			w18.X = 286;
			w18.Y = 9;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.BtnBuscar = new global::Gtk.Button();
			this.BtnBuscar.CanFocus = true;
			this.BtnBuscar.Name = "BtnBuscar";
			this.BtnBuscar.UseUnderline = true;
			this.BtnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox8.Add(this.BtnBuscar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.BtnBuscar]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.txtBuscar = new global::Gtk.Entry();
			this.txtBuscar.CanFocus = true;
			this.txtBuscar.Name = "txtBuscar";
			this.txtBuscar.IsEditable = true;
			this.txtBuscar.InvisibleChar = '•';
			this.hbox8.Add(this.txtBuscar);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.txtBuscar]));
			w20.Position = 1;
			this.fixed1.Add(this.hbox8);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox8]));
			w21.X = 6;
			w21.Y = 131;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 803;
			this.DefaultHeight = 267;
			this.txtId.Hide();
			this.Show();
			this.btnAgregar.Clicked += new global::System.EventHandler(this.OnBtnAgregarClicked);
			this.BtnModificar.Clicked += new global::System.EventHandler(this.OnBtnModificarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
			this.TvListaDepartamentoA.CursorChanged += new global::System.EventHandler(this.OnTvListaDepartamentoACursorChanged);
			this.BtnBuscar.Clicked += new global::System.EventHandler(this.OnBtnBuscarClicked);
		}
	}
}
