
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class ReporteEntradaSalida
	{
		private global::Gtk.Fixed fixed6;

		private global::Gtk.VBox vbox18;

		private global::Gtk.Label label12;

		private global::Gtk.ScrolledWindow scrolledwindow7;

		private global::Gtk.TreeView TvListaAsistencia;

		private global::Gtk.Button btnRegresar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.ReporteEntradaSalida
			this.Name = "COntrolREyS.ReporteEntradaSalida";
			this.Title = global::Mono.Unix.Catalog.GetString("ReporteEntradaSalida");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.ReporteEntradaSalida.Gtk.Container+ContainerChild
			this.fixed6 = new global::Gtk.Fixed();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.vbox18 = new global::Gtk.VBox();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Reporte de asistencia");
			this.vbox18.Add(this.label12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.label12]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox18.Gtk.Box+BoxChild
			this.scrolledwindow7 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow7.WidthRequest = 700;
			this.scrolledwindow7.HeightRequest = 300;
			this.scrolledwindow7.CanFocus = true;
			this.scrolledwindow7.Name = "scrolledwindow7";
			this.scrolledwindow7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow7.Gtk.Container+ContainerChild
			this.TvListaAsistencia = new global::Gtk.TreeView();
			this.TvListaAsistencia.CanFocus = true;
			this.TvListaAsistencia.Name = "TvListaAsistencia";
			this.scrolledwindow7.Add(this.TvListaAsistencia);
			this.vbox18.Add(this.scrolledwindow7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.scrolledwindow7]));
			w3.Position = 1;
			// Container child vbox18.Gtk.Box+BoxChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.vbox18.Add(this.btnRegresar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.btnRegresar]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.fixed6.Add(this.vbox18);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.vbox18]));
			w5.X = 29;
			w5.Y = 20;
			this.Add(this.fixed6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 759;
			this.DefaultHeight = 404;
			this.Show();
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
		}
	}
}
