
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class ADminWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action ArchivoAction;

		private global::Gtk.Action RegistrosAction;

		private global::Gtk.Action ReportesAction;

		private global::Gtk.Action CerrarSesinAction;

		private global::Gtk.Action ExportarComoAction;

		private global::Gtk.Action EmpleadoAction;

		private global::Gtk.Action DepartamentoAction;

		private global::Gtk.Action CargoAction;

		private global::Gtk.Action EmpleadoAction1;

		private global::Gtk.Action DepartamentoAction1;

		private global::Gtk.Action CargoAction1;

		private global::Gtk.Action HoraEntradaYSalidaAction;

		private global::Gtk.Action ExportarComoAction1;

		private global::Gtk.Action ExportarAction;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.MenuBar menubar2;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Label lblHora;

		private global::Gtk.Calendar calendar2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.ADminWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.ArchivoAction = new global::Gtk.Action("ArchivoAction", global::Mono.Unix.Catalog.GetString("Archivo"), null, null);
			this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Archivo");
			w1.Add(this.ArchivoAction, null);
			this.RegistrosAction = new global::Gtk.Action("RegistrosAction", global::Mono.Unix.Catalog.GetString("Registros"), null, null);
			this.RegistrosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Registros");
			w1.Add(this.RegistrosAction, null);
			this.ReportesAction = new global::Gtk.Action("ReportesAction", global::Mono.Unix.Catalog.GetString("Reportes"), null, null);
			this.ReportesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Reportes");
			w1.Add(this.ReportesAction, null);
			this.CerrarSesinAction = new global::Gtk.Action("CerrarSesinAction", global::Mono.Unix.Catalog.GetString("Cerrar Sesión"), null, null);
			this.CerrarSesinAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cerrar Sesión");
			w1.Add(this.CerrarSesinAction, null);
			this.ExportarComoAction = new global::Gtk.Action("ExportarComoAction", global::Mono.Unix.Catalog.GetString("Exportar como"), null, null);
			this.ExportarComoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exportar como");
			w1.Add(this.ExportarComoAction, null);
			this.EmpleadoAction = new global::Gtk.Action("EmpleadoAction", global::Mono.Unix.Catalog.GetString("Empleado"), null, null);
			this.EmpleadoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Empleado");
			w1.Add(this.EmpleadoAction, null);
			this.DepartamentoAction = new global::Gtk.Action("DepartamentoAction", global::Mono.Unix.Catalog.GetString("Departamento"), null, null);
			this.DepartamentoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Departamento");
			w1.Add(this.DepartamentoAction, null);
			this.CargoAction = new global::Gtk.Action("CargoAction", global::Mono.Unix.Catalog.GetString("Cargo"), null, null);
			this.CargoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cargo");
			w1.Add(this.CargoAction, null);
			this.EmpleadoAction1 = new global::Gtk.Action("EmpleadoAction1", global::Mono.Unix.Catalog.GetString("Empleado"), null, null);
			this.EmpleadoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Empleado");
			w1.Add(this.EmpleadoAction1, null);
			this.DepartamentoAction1 = new global::Gtk.Action("DepartamentoAction1", global::Mono.Unix.Catalog.GetString("Departamento"), null, null);
			this.DepartamentoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Departamento");
			w1.Add(this.DepartamentoAction1, null);
			this.CargoAction1 = new global::Gtk.Action("CargoAction1", global::Mono.Unix.Catalog.GetString("Cargo"), null, null);
			this.CargoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Cargo");
			w1.Add(this.CargoAction1, null);
			this.HoraEntradaYSalidaAction = new global::Gtk.Action("HoraEntradaYSalidaAction", global::Mono.Unix.Catalog.GetString("Hora Entrada y Salida"), null, null);
			this.HoraEntradaYSalidaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Hora Entrada y Salida");
			w1.Add(this.HoraEntradaYSalidaAction, null);
			this.ExportarComoAction1 = new global::Gtk.Action("ExportarComoAction1", global::Mono.Unix.Catalog.GetString("Exportar como"), null, null);
			this.ExportarComoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Exportar como");
			w1.Add(this.ExportarComoAction1, null);
			this.ExportarAction = new global::Gtk.Action("ExportarAction", global::Mono.Unix.Catalog.GetString("Exportar"), null, null);
			this.ExportarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exportar");
			w1.Add(this.ExportarAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "COntrolREyS.ADminWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ADminWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.ADminWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar2'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='ExportarAction' action='ExportarAction'/></menu><menu name='RegistrosAction' action='RegistrosAction'><menuitem name='EmpleadoAction' action='EmpleadoAction'/><menuitem name='DepartamentoAction' action='DepartamentoAction'/><menuitem name='CargoAction' action='CargoAction'/></menu><menu name='ReportesAction' action='ReportesAction'><menuitem name='EmpleadoAction1' action='EmpleadoAction1'/><menuitem name='DepartamentoAction1' action='DepartamentoAction1'/><menuitem name='CargoAction1' action='CargoAction1'/><menuitem name='HoraEntradaYSalidaAction' action='HoraEntradaYSalidaAction'/></menu><menu name='CerrarSesinAction' action='CerrarSesinAction'/></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.fixed1.Add(this.menubar2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.menubar2]));
			w2.X = 12;
			w2.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("¡Bienvenido Administrador!");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblHora = new global::Gtk.Label();
			this.lblHora.Name = "lblHora";
			this.lblHora.LabelProp = global::Mono.Unix.Catalog.GetString("Reloj");
			this.vbox1.Add(this.lblHora);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblHora]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.calendar2 = new global::Gtk.Calendar();
			this.calendar2.CanFocus = true;
			this.calendar2.Name = "calendar2";
			this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox1.Add(this.calendar2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.calendar2]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.fixed1.Add(this.vbox1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vbox1]));
			w6.X = 50;
			w6.Y = 49;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 355;
			this.DefaultHeight = 323;
			this.Show();
			this.ArchivoAction.Activated += new global::System.EventHandler(this.OnArchivoActionActivated);
			this.CerrarSesinAction.Activated += new global::System.EventHandler(this.OnCerrarSesinActionActivated);
			
			this.EmpleadoAction.Activated += new global::System.EventHandler(this.OnEmpleadoActionActivated);
			this.DepartamentoAction.Activated += new global::System.EventHandler(this.OnDepartamentoActionActivated);
			this.CargoAction.Activated += new global::System.EventHandler(this.OnCargoActionActivated);
			this.EmpleadoAction1.Activated += new global::System.EventHandler(this.OnEmpleadoAction1Activated);
			this.DepartamentoAction1.Activated += new global::System.EventHandler(this.OnDepartamentoAction1Activated);
			this.CargoAction1.Activated += new global::System.EventHandler(this.OnCargoAction1Activated);
			this.HoraEntradaYSalidaAction.Activated += new global::System.EventHandler(this.OnHoraEntradaYSalidaActionActivated);
			
			this.ExportarAction.Activated += new global::System.EventHandler(this.OnExportarActionActivated);
		}
	}
}
