
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class AdminCargo
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Entry txtId;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.Entry txtBuscar;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtEstado;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Label label4;

		private global::Gtk.Entry txtDescipcion;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBox cbxDepartamento;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Button BtnAgregar;

		private global::Gtk.Button BtnEliminar;

		private global::Gtk.Button BtnModificar;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Label label6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow9;

		private global::Gtk.TreeView TvListaCargo;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button BtnRegresar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.AdminCargo
			this.Name = "COntrolREyS.AdminCargo";
			this.Title = global::Mono.Unix.Catalog.GetString("AdminCargo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.AdminCargo.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtId = new global::Gtk.Entry();
			this.txtId.WidthRequest = 50;
			this.txtId.CanFocus = true;
			this.txtId.Name = "txtId";
			this.txtId.IsEditable = true;
			this.txtId.InvisibleChar = '•';
			this.fixed1.Add(this.txtId);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtId]));
			w1.X = 38;
			w1.Y = 12;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox12.Add(this.btnBuscar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.btnBuscar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.txtBuscar = new global::Gtk.Entry();
			this.txtBuscar.CanFocus = true;
			this.txtBuscar.Name = "txtBuscar";
			this.txtBuscar.IsEditable = true;
			this.txtBuscar.InvisibleChar = '•';
			this.hbox12.Add(this.txtBuscar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.txtBuscar]));
			w3.Position = 1;
			this.fixed1.Add(this.hbox12);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox12]));
			w4.X = 30;
			w4.Y = 49;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.hbox13.Add(this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.hbox13.Add(this.txtNombre);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.txtNombre]));
			w6.Position = 1;
			this.fixed1.Add(this.hbox13);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox13]));
			w7.X = 27;
			w7.Y = 88;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.hbox14.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.txtEstado = new global::Gtk.Entry();
			this.txtEstado.CanFocus = true;
			this.txtEstado.Name = "txtEstado";
			this.txtEstado.IsEditable = true;
			this.txtEstado.InvisibleChar = '•';
			this.hbox14.Add(this.txtEstado);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.txtEstado]));
			w9.Position = 1;
			this.fixed1.Add(this.hbox14);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox14]));
			w10.X = 36;
			w10.Y = 125;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion");
			this.hbox15.Add(this.label4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.label4]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.txtDescipcion = new global::Gtk.Entry();
			this.txtDescipcion.CanFocus = true;
			this.txtDescipcion.Name = "txtDescipcion";
			this.txtDescipcion.IsEditable = true;
			this.txtDescipcion.InvisibleChar = '•';
			this.hbox15.Add(this.txtDescipcion);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.txtDescipcion]));
			w12.Position = 1;
			this.fixed1.Add(this.hbox15);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox15]));
			w13.X = 6;
			w13.Y = 158;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Departamento");
			this.hbox16.Add(this.label5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label5]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.cbxDepartamento = global::Gtk.ComboBox.NewText();
			this.cbxDepartamento.Name = "cbxDepartamento";
			this.hbox16.Add(this.cbxDepartamento);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.cbxDepartamento]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.fixed1.Add(this.hbox16);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox16]));
			w16.X = 42;
			w16.Y = 198;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.BtnAgregar = new global::Gtk.Button();
			this.BtnAgregar.CanFocus = true;
			this.BtnAgregar.Name = "BtnAgregar";
			this.BtnAgregar.UseUnderline = true;
			this.BtnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox17.Add(this.BtnAgregar);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.BtnAgregar]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.BtnEliminar = new global::Gtk.Button();
			this.BtnEliminar.CanFocus = true;
			this.BtnEliminar.Name = "BtnEliminar";
			this.BtnEliminar.UseUnderline = true;
			this.BtnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.hbox17.Add(this.BtnEliminar);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.BtnEliminar]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.BtnModificar = new global::Gtk.Button();
			this.BtnModificar.CanFocus = true;
			this.BtnModificar.Name = "BtnModificar";
			this.BtnModificar.UseUnderline = true;
			this.BtnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.hbox17.Add(this.BtnModificar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.BtnModificar]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.fixed1.Add(this.hbox17);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox17]));
			w20.X = 11;
			w20.Y = 233;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Bienvenido a registro de cargos!");
			this.vbox11.Add(this.label6);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label6]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow9 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow9.WidthRequest = 750;
			this.GtkScrolledWindow9.HeightRequest = 231;
			this.GtkScrolledWindow9.CanFocus = true;
			this.GtkScrolledWindow9.Name = "GtkScrolledWindow9";
			this.GtkScrolledWindow9.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow9.Gtk.Container+ContainerChild
			this.TvListaCargo = new global::Gtk.TreeView();
			this.TvListaCargo.CanFocus = true;
			this.TvListaCargo.Name = "TvListaCargo";
			this.GtkScrolledWindow9.Add(this.TvListaCargo);
			this.vbox11.Add(this.GtkScrolledWindow9);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.GtkScrolledWindow9]));
			w23.Position = 1;
			this.fixed1.Add(this.vbox11);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vbox11]));
			w24.X = 377;
			w24.Y = 13;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.BtnRegresar = new global::Gtk.Button();
			this.BtnRegresar.CanFocus = true;
			this.BtnRegresar.Name = "BtnRegresar";
			this.BtnRegresar.UseUnderline = true;
			this.BtnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.hbox18.Add(this.BtnRegresar);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.BtnRegresar]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			this.fixed1.Add(this.hbox18);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox18]));
			w26.X = 252;
			w26.Y = 233;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1146;
			this.DefaultHeight = 285;
			this.txtId.Hide();
			this.Show();
			this.btnBuscar.Clicked += new global::System.EventHandler(this.OnBtnBuscarClicked);
			this.BtnAgregar.Clicked += new global::System.EventHandler(this.OnBtnAgregarClicked);
			this.BtnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.BtnModificar.Clicked += new global::System.EventHandler(this.OnBtnModificarClicked);
			this.TvListaCargo.CursorChanged += new global::System.EventHandler(this.OnTvListaCargoCursorChanged);
			this.BtnRegresar.Clicked += new global::System.EventHandler(this.OnButton6Clicked);
		}
	}
}
