
// This file has been generated by the GUI designer. Do not modify.
namespace COntrolREyS
{
	public partial class ReporteDepartamento
	{
		private global::Gtk.Fixed fixed4;

		private global::Gtk.VBox vbox17;

		private global::Gtk.Label label10;

		private global::Gtk.ScrolledWindow scrolledwindow5;

		private global::Gtk.TreeView TvListaDepartamento;

		private global::Gtk.Button button9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget COntrolREyS.ReporteDepartamento
			this.Name = "COntrolREyS.ReporteDepartamento";
			this.Title = global::Mono.Unix.Catalog.GetString("ReporteDepartamento");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child COntrolREyS.ReporteDepartamento.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Reporte de departamento");
			this.vbox17.Add(this.label10);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.label10]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.scrolledwindow5 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow5.WidthRequest = 400;
			this.scrolledwindow5.HeightRequest = 300;
			this.scrolledwindow5.CanFocus = true;
			this.scrolledwindow5.Name = "scrolledwindow5";
			this.scrolledwindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow5.Gtk.Container+ContainerChild
			this.TvListaDepartamento = new global::Gtk.TreeView();
			this.TvListaDepartamento.CanFocus = true;
			this.TvListaDepartamento.Name = "TvListaDepartamento";
			this.scrolledwindow5.Add(this.TvListaDepartamento);
			this.vbox17.Add(this.scrolledwindow5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.scrolledwindow5]));
			w3.Position = 1;
			// Container child vbox17.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.vbox17.Add(this.button9);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.button9]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.fixed4.Add(this.vbox17);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.vbox17]));
			w5.X = 20;
			w5.Y = 15;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 442;
			this.DefaultHeight = 398;
			this.Show();
			this.button9.Clicked += new global::System.EventHandler(this.OnButton9Clicked);
		}
	}
}
