
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label6;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label Cedula;

	private global::Gtk.Entry txtAdmin;

	private global::Gtk.Button button3;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label1;

	private global::Gtk.Button btnEmpleado;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Control Entrada y Salida");
		this.fixed1.Add(this.label6);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
		w1.X = 135;
		w1.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Cedula = new global::Gtk.Label();
		this.Cedula.Name = "Cedula";
		this.Cedula.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña");
		this.hbox1.Add(this.Cedula);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Cedula]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtAdmin = new global::Gtk.Entry();
		this.txtAdmin.CanFocus = true;
		this.txtAdmin.Name = "txtAdmin";
		this.txtAdmin.IsEditable = true;
		this.txtAdmin.Visibility = false;
		this.txtAdmin.InvisibleChar = '•';
		this.hbox1.Add(this.txtAdmin);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtAdmin]));
		w3.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Admin");
		this.hbox1.Add(this.button3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button3]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.fixed1.Add(this.hbox1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox1]));
		w5.X = 54;
		w5.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Registrar ");
		this.hbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnEmpleado = new global::Gtk.Button();
		this.btnEmpleado.CanFocus = true;
		this.btnEmpleado.Name = "btnEmpleado";
		this.btnEmpleado.UseUnderline = true;
		this.btnEmpleado.Label = global::Mono.Unix.Catalog.GetString("Empleado");
		this.hbox2.Add(this.btnEmpleado);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnEmpleado]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.fixed1.Add(this.hbox2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox2]));
		w8.X = 142;
		w8.Y = 47;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 421;
		this.DefaultHeight = 144;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.btnEmpleado.Clicked += new global::System.EventHandler(this.OnBtnEmpleadoClicked);
	}
}
